// <auto-generated />
using System;
using Blogging.Infrastructure;
using Blogging.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Softinsight.Services.Blog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20190103170840_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
